### ISSUE TITLE
Onnodige divjes

### ISSUE THREAD

**Issue by Jesse-Kramer** [DamianR2004/the-startup-responsive-interactieve-website#10]
https://github.com/DamianR2004/the-startup-responsive-interactieve-website/blob/9f0bbcbace6c0c3298dcf3c4adc9f1e372dc250d/index.html#L107-L109

Zijn deze div'jes echt nodig? Misschien kan je dit vervangen door een andere element of zelfs helemaal weghalen.

**Comment by DamianR2004** [comment]
Ik heb deze moeten bewaren nadat ik het had geprobeerd om weg te halen. Toch bedankt!
