### ISSUE TITLE
Het lijkt dat je de <g> tag bent vergeten af te sluiten

### ISSUE THREAD

**Issue by Patrickkhr** [DamianR2004/the-startup-responsive-interactieve-website#11]
https://github.com/DamianR2004/the-startup-responsive-interactieve-website/blob/9f0bbcbace6c0c3298dcf3c4adc9f1e372dc250d/index.html#L14

Je bent vergeten de <g> tag af te sluiten.

je kan het element afsluiten door </g> te gebruiken

bron: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/g

**Comment by DamianR2004** [comment]
Is weggehaald, bedankt!
