### ISSUE TITLE
Herhalen van JS code

### ISSUE THREAD

**Issue by Jesse-Kramer** [DamianR2004/the-startup-responsive-interactieve-website#12]
In de code hieronder herhaal je vaker de elementen "Download button" met de queryselector. Waarom herhaal je dit hieronder opnieuw, kan je niet hetzeflde variabel gebruiken die je erboven al hebt gemaakt.
https://github.com/DamianR2004/the-startup-responsive-interactieve-website/blob/9f0bbcbace6c0c3298dcf3c4adc9f1e372dc250d/scripts/script.js#L1-L30

**Comment by DamianR2004** [comment]
Is weggehaald, bedankt!
