### ISSUE TITLE
class Names met streepjes en of hoofdletters

### ISSUE THREAD

**Issue by Jason2426** [DamianR2004/the-startup-responsive-interactieve-website#14]
Allereerst heb je hele nette code 👏 , probeer net zoals bij de rest van je classNames streepjes (-) te gebruiken of hoofdletters voor classnames met meerdere woorden. Dit maakt het beter leesbaar voor jezelf en voor anderen.

https://github.com/DamianR2004/the-startup-responsive-interactieve-website/blob/9f0bbcbace6c0c3298dcf3c4adc9f1e372dc250d/index.html#L107-L108

https://github.com/DamianR2004/the-startup-responsive-interactieve-website/blob/9f0bbcbace6c0c3298dcf3c4adc9f1e372dc250d/index.html#L99

Bij de rest van je HTML elementen doe je dit al wel hier ben je het vergeten!

**Comment by DamianR2004** [comment]
Is opgelost, thanks!
