### ISSUE TITLE
HTML inspringen

### ISSUE THREAD

**Issue by Jason2426** [DamianR2004/the-startup-responsive-interactieve-website#15]
Je HTML is leesbaar maar dit kun je nog verbeteren door beter in te springen op je elementen en als je dat wil tussen elke section witregels toe te voegen. 

https://github.com/DamianR2004/the-startup-responsive-interactieve-website/blob/9f0bbcbace6c0c3298dcf3c4adc9f1e372dc250d/index.html#L10-L116

[Link met hoe je HTML indent (inspringt)](https://www.freecodecamp.org/news/how-to-indent-in-html-and-why-it-is-important/#:~:text=When%20writing%20HTML%20it%20is,two%20spaces%20to%20the%20right.&text=This%20will%20make%20your%20code,child%20and%20parent%20HTML%20elements.)

Oplossing ^

**Comment by DamianR2004** [comment]
Opgelost, thanks!
