### ISSUE TITLE
Html "input" element wordt afgesloten met eindtag

### ISSUE THREAD

**Issue by annelinderaadsheer** [DamianR2004/the-startup-responsive-interactieve-website#16]
input element wordt afgesloten met eindtag.

Je kunt inplaats van het element af te sluiten hem bijvoorbeeld zo laten: <input>

Bron: https://validator.w3.org/nu/?doc=https%3A%2F%2Fdamianr2004.github.io%2Fthe-startup-responsive-interactieve-website%2F

**Comment by DamianR2004** [comment]
Is opgelost, bedankt!
