### ISSUE TITLE
Logo heading

### ISSUE THREAD

**Issue by SamaraFellaDina** [DamianR2004/the-startup-responsive-interactieve-website#2]
```html
src="./assets/logo-color-on-white.jpeg"
```

Dit logo is nogal groot en niet handig voor het maken van een header lijkt mij. 

Ik heb zelf dit logo gebruikt

![Enrise logo color rectangle](https://github.com/DamianR2004/the-startup-responsive-interactieve-website/assets/144009778/f07c0f73-3bcd-4443-8cb0-5f5d6739ec56)

**Comment by DamianR2004** [comment]
Aangepast, thanks!
