### ISSUE TITLE
Lekker bezig!

### ISSUE THREAD

**Issue by SamaraFellaDina** [DamianR2004/the-startup-responsive-interactieve-website#3]
Goed bezig! ik zie dat je gebruik maakt van fall-back fonts en je hebt het formulier goed opgebouwd. Ook zie ik veel `alt` elementen, goede toegankelijkheid. Ik zou nu beginnen met cssen!

![](https://media.giphy.com/media/hUhARUMJB4OsRMXJ6l/giphy.gif)

**Comment by DamianR2004** [comment]
Thanks!😁
