### ISSUE TITLE
line spacing

### ISSUE THREAD

**Issue by driezie** [DamianR2004/the-startup-responsive-interactieve-website#4]
https://github.com/DamianR2004/the-startup-responsive-interactieve-website/blob/76b4f1ffbe96a983daac504d6f5fd819ad69a98f/index.html#L82-L87

Probeer als bij deze voorbeeld maar 1 extra lijn te maken zodat er niet teveel space hierzo in zit. Dit maakt de code een stuk duidelijker

**Comment by DamianR2004** [comment]
opgelost, thanks!
