### ISSUE TITLE
Betere namen gebruiken voor custom properties

### ISSUE THREAD

**Issue by Metehan2003** [DamianR2004/the-startup-responsive-interactieve-website#6]
https://github.com/DamianR2004/the-startup-responsive-interactieve-website/blob/58f556d932f2b317e438867cd2db2ae29403c93d/docs/styles.css#L16-L26

Je hebt voor de custom properties namen gebruikt die niet duidelijk uit elkaar te halen zijn. Je kan het best aparte namen gebruiken die niet veel op elkaar lijker voor duidelijkheid.

**Comment by DamianR2004** [comment]
Gedaan, thanks!
