### ISSUE TITLE
Alt atribuut is niet toegestaan in path element. (Validator)

### ISSUE THREAD

**Issue by Jesse-Kramer** [DamianR2004/the-startup-responsive-interactieve-website#7]
Alt atribuut is niet toegestaan in path element.
https://github.com/DamianR2004/the-startup-responsive-interactieve-website/blob/9f0bbcbace6c0c3298dcf3c4adc9f1e372dc250d/index.html#L34

Misschien kan je de alt atribuut eruit halen

Lees hier meer over het path element:
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/path

**Comment by DamianR2004** [comment]
Is opgelost, thanks!
