### ISSUE TITLE
Je lijkt een input tag af te sluiten.

### ISSUE THREAD

**Issue by Patrickkhr** [DamianR2004/the-startup-responsive-interactieve-website#8]
https://github.com/DamianR2004/the-startup-responsive-interactieve-website/blob/9f0bbcbace6c0c3298dcf3c4adc9f1e372dc250d/index.html#L93-L101

Je sluit een input element af.

Je hoeft de input niet af te sluiten.

**Comment by DamianR2004** [comment]
Opgelost✅ Bedankt!
