### ISSUE TITLE
Random input end tag.

### ISSUE THREAD

**Issue by Jesse-Kramer** [DamianR2004/the-startup-responsive-interactieve-website#9]
https://github.com/DamianR2004/the-startup-responsive-interactieve-website/blob/9f0bbcbace6c0c3298dcf3c4adc9f1e372dc250d/index.html#L100-L102

Je hebt een random input element end tag. Een input element hoef je niet af te sluiten.

Meer informatie hier: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

**Comment by DamianR2004** [comment]
Opgelost ✅ Thanks!
